server:
  port: 8083
spring:
  application:
    name: prod-user-microservice
  config:
    name: prod-user-microservice
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: prod
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true