server:
  port: 8080

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
    actuator:
      enabled: true
    security:
      enabled: false

  endpoint:
    restart:
      enabled: true
spring:
  application:
    name: dev-user-microservice
  config:
    name: user-microservice
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

logging:
  level:
    org:
      springframework:
        web: DEBUG